# Generated by Django 4.2.16 on 2024-11-04 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_profit', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='止盈点位')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='获取策略的日期')),
                ('buy_01', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='止盈点一')),
                ('buy_02', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='止盈点二')),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='止损点')),
                ('code', models.CharField(max_length=11, verbose_name='股票代码')),
                ('name', models.CharField(max_length=12, verbose_name='股票名称')),
            ],
            options={
                'verbose_name': '股票策略测试表',
                'db_table': 'test_static',
            },
        ),
    ]
