# Generated by Django 4.2.16 on 2024-11-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbasic',
            name='exchange',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='industry',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='list_status',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='上市状态'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='market',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='市场类别'),
        ),
    ]
