# Generated by Django 4.2.16 on 2024-11-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_stockbasic_exchange_alter_stockbasic_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecal',
            name='exchange',
            field=models.CharField(max_length=10, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='tradecal',
            name='is_open',
            field=models.CharField(max_length=10, verbose_name='是否交易'),
        ),
        migrations.AlterField(
            model_name='tradecal',
            name='pretrade_date',
            field=models.CharField(max_length=10, verbose_name='上一个交易日'),
        ),
    ]
